//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int Id { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Company_id { get; set; }
        public Nullable<int> City_id { get; set; }
        public Nullable<int> Terminal_id { get; set; }
        public Nullable<int> Gate_id { get; set; }
        public Nullable<int> Runway_id { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual City City { get; set; }
        public virtual Company Company { get; set; }
        public virtual Gate Gate { get; set; }
        public virtual Runway Runway { get; set; }
        public virtual Terminal Terminal { get; set; }
    }
}
